### PR TITLE
Update in util.js

### PR DESCRIPTION
**Pull request by hawckins**
Brace expression is not working, if the object has single value, so I did a check to verify the object length and passing the mask accordingly.

### CODE REVIEW

**Review by L2jLiga — APPROVED** [review]
Cool, thanks!

**Comment by L2jLiga** [comment]
I will release new version soon

**Comment by hawckins** [comment]
> I will release new version soon

May I know tentatively when are you planning to release? because we are waiting to be updated in our build system. Thanks a lot for merging

**Comment by L2jLiga** [comment]
released v2.0.1

**Pull request merged**
